plugins = (
    "build-timeout",
    "docker-build-publish",
    "docker-plugin",
    "jenkinslint",
    "git",
    "github",
    "build-pipeline-plugin",
    "delivery-pipeline-plugin",
    "workflow-aggregator",
    "docker-workflow",
    "buildgraph-view",
    "greenballs",
    "backup",
    "swarm",
)
    #"pipeline-plugin",
    #"jenkinslint-plugin",
